In [3]:
from numpy import random
print(random.randint(1,100))# random int in given range
print(random.rand())# random floating point no.



81
0.6735758365437694


In [4]:
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))

[37 44 28]
[[81 12 15 19]
 [ 8 57 40 17]
 [18 18 23 68]]


In [5]:
a= random.randint(100,size=(3,2)).ravel()
a

array([59, 46, 79,  1,  7,  2])

In [6]:
random.choice(a)

7

In [7]:
# single element will be selected
random.choice([1,2,3,4,5],size=(3,4))

array([[2, 5, 5, 5],
       [4, 3, 2, 1],
       [1, 2, 2, 4]])

In [8]:
# for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[4, 1, 1, 5],
       [5, 5, 5, 5],
       [4, 1, 4, 1],
       [5, 3, 3, 3]])

### pandas:
1. data manipulation,analysis and cleaning
2. tabular,unlablel


### creating a data frame
1. using 2 dictionaries
2. simple dictionary -->DataFrame

In [9]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 ={'a':5,'b':6,'c':7,'d':7,'f':9}
data ={ "first":dict1,"second":dict2}
df = pd.DataFrame(data,dtype="int32")
df

first  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     7.0
e    5.0     NaN
f    NaN     9.0

In [14]:
#simple dictionary
d1={"name":["nbs","sri","uuu"],"address":["hyd","knl","TN"]}
df1=pd.DataFrame(d1)
df1

name address
0  nbs     hyd
1  sri     knl
2  uuu      TN

###  using series

In [10]:
s1 =  pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 =  pd.Series([11,12,13,14,15,16,17,18,19,20])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column  column2 column3
0       1       11       a
1       2       12       b
2       3       13       c
3       4       14       d
4       5       15       e
5       6       16       f
6       7       17       g
7       8       18       h
8       9       19       i
9      10       20       j

### selecting data from the data frame:
1. loc:
2. iloc:

In [11]:
df3["column2"]

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
9    20
Name: column2, dtype: int64

In [12]:
df3[["column2","column3"]]

column2 column3
0       11       a
1       12       b
2       13       c
3       14       d
4       15       e
5       16       f
6       17       g
7       18       h
8       19       i
9       20       j

In [13]:
# single colunm
df3.loc[:,"column"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column, dtype: int64

In [14]:
df3.loc[:,["column","column2"]]

column  column2
0       1       11
1       2       12
2       3       13
3       4       14
4       5       15
5       6       16
6       7       17
7       8       18
8       9       19
9      10       20

In [15]:
df3.loc[0:5,["column","column2"]]

column  column2
0       1       11
1       2       12
2       3       13
3       4       14
4       5       15
5       6       16

In [16]:
type(df3)

pandas.core.frame.DataFrame

In [17]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column, dtype: int64

In [18]:
df3.iloc[0:4,0:1]

column
0       1
1       2
2       3
3       4

### retriving the information of data base 

In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column     10 non-null int64
column2    10 non-null int64
column3    10 non-null object
dtypes: int64(2), object(1)
memory usage: 320.0+ bytes


In [20]:
df3.shape

(10, 3)

In [21]:
df3.columns

Index(['column', 'column2', 'column3'], dtype='object')

In [22]:
df3.index

RangeIndex(start=0, stop=10, step=1)

viewing data from DataFrame:
1. head()
2. tail()
3. sample()==> random from data frame

In [23]:
df3.head(3)

column  column2 column3
0       1       11       a
1       2       12       b
2       3       13       c

In [24]:
df3.tail(3)

column  column2 column3
7       8       18       h
8       9       19       i
9      10       20       j

In [25]:
df3.sample(2)

column  column2 column3
1       2       12       b
9      10       20       j

In [26]:
df3.describe()

column   column2
count  10.00000  10.00000
mean    5.50000  15.50000
std     3.02765   3.02765
min     1.00000  11.00000
25%     3.25000  13.25000
50%     5.50000  15.50000
75%     7.75000  17.75000
max    10.00000  20.00000

### changing ur col and row names:

In [27]:
df3=df3.rename(columns={"column":"first","column1":"second","column2":"third"})

In [28]:
df3

first  third column3
0      1     11       a
1      2     12       b
2      3     13       c
3      4     14       d
4      5     15       e
5      6     16       f
6      7     17       g
7      8     18       h
8      9     19       i
9     10     20       j

In [29]:
df3

first  third column3
0      1     11       a
1      2     12       b
2      3     13       c
3      4     14       d
4      5     15       e
5      6     16       f
6      7     17       g
7      8     18       h
8      9     19       i
9     10     20       j

In [30]:
df3.rename(columns={ "second":"col2","third":"col3"},inplace=True)

In [31]:
df3

first  col3 column3
0      1    11       a
1      2    12       b
2      3    13       c
3      4    14       d
4      5    15       e
5      6    16       f
6      7    17       g
7      8    18       h
8      9    19       i
9     10    20       j